#! /bin/sh
if (test "x$#" != "x1") ; then
  echo "Usage: $0 [--libs | --cxxflags | --cppflags]"
  exit;
fi

LIBRARY="-lpthread -lasound -ljack  -L/usr/local/lib"
CXXFLAGS="-O2 -Wall -Wextra"
CPPFLAGS=" -I/usr/local/include  -DHAVE_GETTIMEOFDAY  -D__UNIX_JACK__ -D__LINUX_ALSA__"

if (test "x$1" = "x--libs") ; then
  echo "$LIBRARY -lrtaudio"
elif (test "x$1" = "x--cxxflags") ; then
  echo "$CXXFLAGS"
elif (test "x$1" = "x--cppflags") ; then
  echo "$CPPFLAGS"
else
  echo "Unknown option: $1"
fi
